version: '3'
services:
  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    restart: "no"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - HEXtoRGB
      - HSLtoHEX
      #- HSLtoRGB

  HEXtoRGB:
    image: hex2rgb
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.HEXtoRGB.rule=PathPrefix(`/HEXtoRGB`)"
      - "traefik.http.routers.HEXtoRGB.middlewares=HEXtoRGB-stripprefix"
      - "traefik.http.middlewares.HEXtoRGB-stripprefix.stripprefix.prefixes=/HEXtoRGB"
  
  HSLtoHEX:
    image: hsl2hex
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.HSLtoHEX.rule=PathPrefix(`/HSLtoHEX`)"
      - "traefik.http.routers.HSLtoHEX.middlewares=HSLtoHEX-stripprefix"
      - "traefik.http.middlewares.HSLtoHEX-stripprefix.stripprefix.prefixes=/HSLtoHEX"

  HSLtoRGB:
    image: hsl2rgb
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.HSLtoRGB.rule=PathPrefix(`/HSLtoRGB`)"
      - "traefik.http.routers.HSLtoRGB.middlewares=HSLtoRGB-stripprefix"
      - "traefik.http.middlewares.HSLtoRGB-stripprefix.stripprefix.prefixes=/HSLtoRGB"